### ISSUE TITLE
Vector.<> can't be used

### ISSUE THREAD

**Issue by ghost** [Corsaair/redtamarin#130]
`Vector.<*>` crashes `redshell`, but the rest throw a `#1127` error. Is it unimplemented?

```
$ redshell -repl

Vector.<*> // Reflect
avmplus crash: exception 0xC0000005 occurred
// Writing minidump crash log to avmplusCrash.dmp

new Vector.<uint> 
// TypeError: Error #1127
```

**Comment by hydroper** [comment]
@zwetan So is it simply ignoring `Vector.<>` ?

**Comment by hydroper** [comment]
@zwetan Is it hard to make it work?

**Comment by ghost** [comment]
The issue wasn't `Vector` still, somehow.
