### ISSUE TITLE
[AVMPlus] User namespaces unimplemented

### ISSUE THREAD

**Issue by ghost** [Corsaair/redtamarin#135]
### Issue

Somehow I can't define properties using custom namespace, even when under package block.

### Expected behavior

The following should not throw exception in AVM2:

```
namespace qux
class A {
    qux var x: Number
}
```

### Actual behavior

Run `redshell build.as3` and get:

```
Error: build.as3:4: Internal error: Defintions in user-defined namespaces not implemented
   3 |     Q var x: Number
```

**Comment by zwetan** [comment]
that is because you are evaluating code, the eval have many limitations
you need to compile to bytecode first and run it
`$ redshell build.abc`
