### ISSUE TITLE
What do you think of Dalvik bytecode?

### ISSUE THREAD

**Issue by ghost** [Corsaair/redtamarin#136]
An easy way to support Red Tamarin on Android phones is by targetting Dalvik bytecode (dex), which is like JVM class bytecode. This is high-level register-based bytecode and supports `instance-of`-like instructions, just like JVM.

Things to consider:
- `default xml namespace = ns`: this instruction would require a way to retrieve/modify a frame internal property [[DefaultXMLNamespace]] (as seen in E4X spec.). Workaround: change the behavior of this statement (which doesn't matter for most users).
- Java frame variables are final (read-only) when captured by nested activations. Workaround is creating a class and instantiating a new object containing writable variables.

Dalvik runtime defines Java classes. For example, the class [`java.lang.System`](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html) is crucial for the command-line. To run a DEX in Termux, I think one uses the `dalvikvm` command.

Since Termux does not run JAR yet, UserLAnd will have to be used for development instead, because Ubuntu supports the package `openjdk-jdk-8`.

Reference:
- [Bytecode Format](https://source.android.com/devices/tech/dalvik/dalvik-bytecode)

**Comment by Hydroper** [comment]
It is much easier than targetting armv7a or arm64.

**Comment by Hydroper** [comment]
Another good point: the Android platform support won't be so vulnerable to bugs, thus less mainteinance time!

**Comment by ROBERT-MCDOWELL** [comment]
interesting. does it mean that this ART/Dalvik can be used to embed any kind of software?

**Comment by Hydroper** [comment]
They usually build Kotlin/Java to target dex. .NET (C#) too targetted dex ([Reddit](https://www.reddit.com/r/csharp/comments/1c04bk/introducing_dot42_a_c_compiler_for_androids/)).

**Comment by ROBERT-MCDOWELL** [comment]
did you check ruffle project?
https://github.com/ruffle-rs/ruffle

**Comment by ghost** [comment]
Oh, yeah, but ultimately I'm able to run Flash Player in any phone with [Webgenie Flash Browser](https://play.google.com/store/apps/details?id=com.webgenie.swfplay2&hl=en). Previously I was using UserLAnd application's Ubuntu shell (with openjdk-jdk-8 package) to build AS3 to SWF/SWC in my Android device and I could run SWFs with this Webgenie application.

**Comment by Hydroper** [comment]
But Ruffle is interesting, since it may turn better than this buggy application.

**Comment by zwetan** [comment]
read [Redtamarin's mission statement](https://github.com/Corsaair/redtamarin#mission-statement)

> To support the use of the AS3 language for cross-platform **command-line executable**,
as single exe either for the desktop or the server, as scripts for automation,
as tools for the Flash Platform community.

Redtamarin's goal is to produce CLI apps
you need to produce a GUI app to publish on Android,
as such Android is not a target platform, or any other mobile platform for that matter

also our whole code base is heavily based on the ActionScript Virtual Machine (AVM2)
and we see no reason to switch or change or target other VM, feel free to do that on your own project

this is not a discussion forum

**Comment by ghost** [comment]
> Redtamarin's goal is to produce CLI apps
you need to produce a GUI app to publish on Android,
as such Android is not a target platform, or any other mobile platform for that matter

Oh, actually Termux can run `dex` using the command `dalvikvm`. Here is an example, not specific to Termux but to ADB: [http://www.herongyang.com](http://www.herongyang.com/Android/shell-dalvikvm-Command-to-Run-Java-Application.html).

However, so far it seems like Termux does not have a JRE package so far, thus ASC 2.0 cannot be run from Termux, but UserLAnd does; but in turn I don't know whether UserLAnd supports or not the `dalvikvm` command.

I'd be happy to use `redbean` and ASC 2.0 in Termux.

**Comment by zwetan** [comment]
> I'd be happy to use redbean and ASC 2.0 in Termux.

it is a non-goal to compile and/or run redtamarin tools under Android, Termux, and/or ARM etc.

see [Compiling Redtamarin](https://github.com/Corsaair/redtamarin/wiki/CompilingRedtamarin)
and [Supported Operating System](https://github.com/Corsaair/redtamarin/wiki/SupportedOperatingSystem)

before posting anymore nonsense do read the documentation available on the wiki

**Comment by ROBERT-MCDOWELL** [comment]
@Hydroper 
I think it's better for you to fork and play with your own experiments, you won't have any cooperation here.

**Comment by zwetan** [comment]
What are you contributing to the project exactly ?

it is not because the project is open source that you can come and change its direction on a whim

  - by ignoring the mission statement that define clear goals and non-goals
  - by not reading the documentation on the wiki
  - by using issues to build up your own completely off-topic conversation

you are disrespecting the project and distracting the people actually working on the project

educate yourselves
[How Open Source Projects Survive Poisonous People](https://techdevguide.withgoogle.com/resources/how-open-source-projects-survive-poisonous-people/)

continue this behaviour and you will be blocked

**Comment by al-sabr** [comment]
Dude you sound like a religious cult with a mission. GFYS
