### ISSUE TITLE
Capability: ActionScript 2

### ISSUE THREAD

**Issue by zwetan** [Corsaair/redtamarin#138]
Executing AS2

**Comment by zwetan** [comment]
No

Reasons:
  - AVM2 is open sourced, AVM1 is not
  - our focus is AS3, not AS1 nor AS2

**Comment by zwetan** [comment]
more infos

AVM1 is the ActionScript virtual machine used to run ActionScript 1.0 and 2.0
AVM2 is the ActionScript virtual machine used to run ActionScript 3.0

Only AVM2 been open sourced in Tamarin / AVMPlus
we could add an AVM1 engine to support AS1 or AS2 execution
but we consider this out of scope even if it could be possible

**Comment by ROBERT-MCDOWELL** [comment]
AVM1 compiler is planned to be developed here (no deadline)
https://github.com/ruffle-rs/ruffle

**Comment by zwetan** [comment]
yeah but no

  - our code base is C/C++ not Rust
  - not our goal to support AS1 or AS2 or AVM1 (hence why it is out of scope)
  - there are already open source AVM1 interpreters like [Gnash](https://github.com/strk/gnash)

**Comment by zwetan** [comment]
API Scrub

  - this impact `flash.display.Loader` class
    if we try to load AVM1 SWF (SWF8 and earlier) it will throw an error 2111
    "Security.disableAVM1Loading is true so the current load of the ActionScript 1.0/2.0 SWF file has been blocked."
  - this impact `flash.system.Security` class
     the property `Security.disableAVM1Loading` is always `true`
     if we try to set it to `false` an error 2110 is thrown
     "The value of Security.disableAVM1Loading cannot be set unless the caller can access the stage and is in an ActionScript 3.0 SWF file."
    we consider we do not have access to the `stage` because we do not supports GUI rendering
