### ISSUE TITLE
build  err

### ISSUE THREAD

**Issue by matrix3d** [Corsaair/redtamarin#184]
the win10 have uname -r?
compile-binaries-task:

before:
    [mkdir] Created dir: F:\proj\redtamarin\bin-debug-32\release
     [echo] release32 flags:
     [echo] --target=i386-windows
     [exec] Traceback (most recent call last):
     [exec]   File "../../src/configure.py", line 131, in <module>
     [exec]     sourcefile = 'core/avmplus.h')
     [exec]   File "F:\proj\redtamarin\src\build\configuration.py", line 90, in __init__
     [exec]     self._host = _configGuess(options)
     [exec]   File "F:\proj\redtamarin\src\build\configuration.py", line 36, in _configGuess
     [exec]     cputest = build.process.run_for_output(['uname', '-m'])
     [exec]   File "F:\proj\redtamarin\src\build\process.py", line 17, in run_for_output
     [exec]     raise Exception("Command failed: '" + cmd + "'")
     [exec] Exception: Command failed: 'uname -m'

**Comment by zwetan** [comment]
see [Windows Setup](https://github.com/Corsaair/redtamarin/wiki/WindowsSetup)
also see [extras/cygwin/redtamarin-dev-setup.bat](https://github.com/Corsaair/redtamarin/blob/master/extras/cygwin/redtamarin-dev-setup.bat)

to build under Windows you need to install Cygwin
Cygwin provide uname

**Comment by matrix3d** [comment]
https://github.com/matrix3d/matrix3d.github.io/wiki/%E7%BC%96%E8%AF%91redtamarin

**Comment by zwetan** [comment]
you seem to think you just need to fix bug till the whole thing compile, it will not work

you have to follow EVERYTHING described here [Windows Setup](https://github.com/Corsaair/redtamarin/wiki/WindowsSetup)

the last "bug" you mention
> `[exec] /cygdrive/f/proj/redtamarin/src/build/cygwin-wrapper.sh: 绗? 78 琛?:
exec: cl.exe: 鏈壘鍒?`

are explained under [Visual Studio](https://github.com/Corsaair/redtamarin/wiki/WindowsSetup#visual-studio) and [Configure your Visual Studio environment](https://github.com/Corsaair/redtamarin/wiki/WindowsSetup#configure-your-visual-studio-environment)

if you don't setup the Visual Studio environment variables then
under Cygwin Bash prompt
`$ cl` will fail

when it should returns
```
Microsoft (R) C/C++ Optimizing Compiler Version 16.00.40219.01 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
```

few advices
  - you can not use any Visual Studio, it HAS TO be
     Visual Studio 2010 Express All-in-One
  - you can not use any Windows, it has to be a 64-bit system
     ideally Windows 8.1 Pro 64-bit or Windows 10 Pro 64-bit
  - you HAVE TO follow every step of the setup, it is not optional

yeah compiling C++ is hard
