### ISSUE TITLE
DECLARE_SLOTS_FileClass is undefined

### ISSUE THREAD

**Issue by ghost** [Corsaair/redtamarin#54]
Trying to build the avm2010.sln/vcxproj on Windows 8.1:

error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   d:\projects-download\redtamarin\src\shell\FileClass.h   49

(DECLARE_SLOTS_FileClass is undefined)

**Comment by zwetan** [comment]
assuming you followed [Windows Setup](https://github.com/Corsaair/redtamarin/wiki/WindowsSetup)
you also must have read [Compiling Redtamarin](https://github.com/Corsaair/redtamarin/wiki/CompilingRedtamarin)

the build is meant to run from the command line,
not from a Visual Studio solution.

The problem you see in VS must be related to something that is not used/needed anymore
eg. the `FileClass.h`

**Comment by zwetan** [comment]
see in [avmshell.h](https://github.com/Corsaair/redtamarin/blob/ed82fd7aa7cdabdac8c403b2f39967ab94f26088/src/shell/avmshell.h#L88)

see also [src/shell/manifest.mk](https://github.com/Corsaair/redtamarin/blob/master/src/shell/manifest.mk)

`FileClass.h` / `FileClass.cpp` are not used/included anymore

**Comment by ghost** [comment]
Thank you. I was trying to build using the avm2010.vcxproj which still had the FileClass.cpp source. Is this an indication that the sln/vcxproj should not be used any more, but rather use makefiles?

**Comment by ghost** [comment]
Assuming yes to my question, perhaps the obsolete project files should be removed too.

**Comment by zwetan** [comment]
VS solutions, Xcode projects etc are kept for reference but not used for compilation

**Comment by ghost** [comment]
OK, that makes sense.
