### ISSUE TITLE
Variable System is not defined

### ISSUE THREAD

**Issue by ghost** [Corsaair/redtamarin#55]
Running `avmshell-debug-debugger.exe` with a flash file that contains the following:

> import flash.system.System;
> trace(System.totalMemory);

gives the following error:

> ReferenceError: Error #1065: Variable System is not defined.

Looking at the source code, the `System` class seems to be implemented though.

**Comment by zwetan** [comment]
the different avmshell found under `/build/shell` are builds of the Tamarin project
found on mozilla [tamarin-redux](http://hg.mozilla.org/tamarin-redux) repository

which later have been moved and slightly updated
on [adobe-flash/avmplus](https://github.com/adobe-flash/avmplus)
(tamarin-redux/rev/f5191c18b0e4)

see their [shell_toplevel.as](http://hg.mozilla.org/tamarin-redux/file/tip/shell/shell_toplevel.as)
for the API available in `avmplus.*`, `flash.*`, etc.

Redtamarin is based on Tamarin but extend it with more API implementations
the 2 API are not compatible

Tamarin implement
`avmplus.System` to use `System.totalMemory`

Redtamarin implement
`flash.system.System` to use `System.totalMemory`
to be API compatible with Flash and AIR API

**Comment by ghost** [comment]
Thank you
