### ISSUE TITLE
Allow to generate redtamarin compatible SWF files from MXMLC

### ISSUE THREAD

**Issue by zwetan** [Corsaair/redtamarin#66]
It would be easier to get people started with Redtamarin to be able to do the foillowing scenario
- install redtamarin-sdk
- install Flex SDK for a "special" config
- in the FLex SDK, replace the `playerglobal.swc`  
  with `redtamarin.swc` (renamed as playerglobal.swc)
- Open Flash Builder
- select this "special Flex SDK
- write AS3 code
- compile the project (eg. "Build All")
- be able to run  
  `$ redtamarin bin-debug/projectname.swf`

**Comment by zwetan** [comment]
We got almost everything but we need to compile `flash.display.Sprite` in the redtamarin bytecode

why ?
when you reuse other SWC, those have a hard dependency on `flash.display.Sprite`

for now, you can compile a SWF if you use only the API from redtamarin.swc
it will work

but if you use an external SWC, for ex: `ansilib.swc` (with "merge into code")
even if the final SWF contains the bytecode of the library
the final SWF can not run as it misses the `flash.display.Sprite` class

**Comment by ajwfrost** [comment]
---

@zwetan moved this issue to 
#77 Add support for SWF with LZMA compression

it would be preferable to not mix different issues that have nothing to do with each other

**Comment by ajwfrost** [comment]
[redtamarin-config.txt](https://github.com/Corsaair/redtamarin/files/165203/redtamarin-config.txt)
Adding the config file as a txt, needs renaming to xml..

**Comment by zwetan** [comment]
Look @ajwfrost I appreciate the participation but what you are posting have nothing to do with the original issue.

"generate redtamarin compatible SWF files from MXMLC"
means
- be able to use Flash Builder to generate a SWF  
  (by default it uses MXMLC)
- add or change the minimum elements in the settings  
  to make that work

So far we discovered that duplicating a Flex SDK and replacing the `playerglobal.swc`
with our own `redtamarin.swc` renamed to `playerglobal.swc`
allow to build the SWF from Flex builder
and then later run the SWF with `redshell` on the command line

there are still some bugs
but to make this work we need to change some code in redtamarin itself
I really don't see how using the redtamarin-config.xml changes things?
for what? not renaming the SWC ?

**Comment by zwetan** [comment]
the LZMA compression may be a problem but not a high priority one

for now, the goal is that:
- use Adobe Flex SDK 4.6
- do not use LZMA compression
- try to patch as few as possible in the Flex SDK  
  to make things work

**Comment by ajwfrost** [comment]
Uploaded project to [https://www.dropbox.com/s/9vzie7merlcm1c0/MainApp.zip?dl=0](url)

**Comment by ajwfrost** [comment]
Okay, sorry I'm mixing up my threads here :-(  
This issue = generating redtamarin-compatible SWF using MXMLC which is what I've got working (but via FlashDevelop, not via Flash Builder). Not changing the filenames or anything, just changing the config that MXMLC is given to compile against. If you wanted it to work via Flash Builder I could have a look at that some time....

**Comment by zwetan** [comment]
added the required classes like `Sprite`, `Security` etc.

**Comment by zwetan** [comment]
if we compile only a main class from Flash Builder
everything works well, we can run the SWF from redshell

but if we use a SWC library
the main class can not find its definition

this is due to how `ShellCore` is parsing the SWF and executing the different ABC tags

with a simple test
- test_one is the main class
- using references from base64lib.swc

here the dump of the SWF
`$ ./abcdump -api bin-debug/test_one.swf`

```
---- ABC #1 test_one.abc
  class test_one extends Object

    class test_one function test_one():*
---- ABC #2 test_one1.abc (eg. the base64lib)
  class encoding.base64::Base64Encoder extends Object

    class encoding.base64::Base64Encoder function encoding.base64::Base64Encoder():*
        class encoding.base64::Base64Encoder var insertNewLines:Boolean = true

        class encoding.base64::Base64Encoder function reset():void

        class encoding.base64::Base64Encoder function encodeBytes(flash.utils::ByteArray,uint,uint):void

        class encoding.base64::Base64Encoder function encodeUTFBytes(String):void

        class encoding.base64::Base64Encoder function encode(String,uint,uint):void

        class encoding.base64::Base64Encoder function toString():String
        class encoding.base64::Base64Encoder static const CHARSET_UTF8:String = "UTF-8"
        class encoding.base64::Base64Encoder static const MAX_BUFFER_SIZE:uint = 32767
        class encoding.base64::Base64Encoder static var newLine:uint = 10

  class encoding.base64::Base64Decoder extends Object

    class encoding.base64::Base64Decoder function encoding.base64::Base64Decoder():*

        class encoding.base64::Base64Decoder function reset():void

        class encoding.base64::Base64Decoder function decode(String):void

        class encoding.base64::Base64Decoder function toByteArray():flash.utils::ByteArray

  function encoding.base64::encodeBase64(String,Boolean):String

  function encoding.base64::decodeBase64(String):String

  function encoding.base64::encodeBase64bytes(flash.utils::ByteArray,uint,uint,Boolean):String

  function encoding.base64::decodeBase64bytes(String):flash.utils::ByteArray
----
```

because we need to instantiate our main class
eg. `var app:test_one = new test_one();`

the ABC `#1` is marked "executable
and
the ABC `#2` is marked "lazy"

when redshell parse the SWF, it tries to execute right away the ABC `#1`
but did not parsed yet the ABC `#2`

so any reference to any definitions in base64lib are not found
and it fails

there are different ways to solve that

a complex one would be to save the ABC `#1` name while it is parsed
not execute it (make it deferred, or simply not add `var app:test_one = new test_one();`)
and when the full SWF has been parsed use reflection/dynamic code
to instantiate the "main class" (from the C++ frontend)

another way (simpler but a bit hairy) is to not define in the main class
`var app:test_one = new test_one();` and instead rely on the `atExit()`
mechanism  and instantiate a class via reflection from the AS3 frontend.

for example:

``` as3
       Program.atExit( function():void {
           new test_one();
       } );
```

by removing the executable bit from the main class
this one does not execute but then before the program exit we then
execute the main class

it does work, some support methods have been added in `Program`
to do that

``` as3
Program.start( "test_one" );
```

it's not perfect, but can be improved/updated later
