### ISSUE TITLE
FlashDevelop project template

### ISSUE THREAD

**Issue by Neverbirth** [Corsaair/redtamarin#73]
Would be nice to see a project template for FlashDevelop that could be installed from AppMan. [AppMan entries file](https://github.com/fdorg/flashdevelop/blob/development/appman.xml).

**Comment by zwetan** [comment]
I m not sure what is appman, for quickly looking at the XML
it seems it is something to configure in FD to install other exe

the redtamarin-sdk is not an exe installer

not sure of what you want ?

**Comment by Neverbirth** [comment]
AppMan is a simple application that allows to distribute and manage third party content for FD, it can be other applications, but also plugins, custom themes, templates, etc. The proposal would be to create a project template that would allow to easily target redtamarin projects, and add an entry in the appman.xml so anyone can quickly find and install it in there.

**Comment by zwetan** [comment]
> AppMan is a simple application that allows to distribute and manage third party content for FD

OK, but again we distribute redtamarin-sdk as a debian package
and for windows we have a dependency on installing Cygwin

> The proposal would be to create a project template that would allow to easily target redtamarin projects

a project template could probably work

> add an entry in the appman.xml so anyone can quickly find and install it in there.

this would probably not work

appman as I see it act as package manager in the context of FD,
it may work OK for `exe`, `msi`, `zip` files
but I doubt it would work for `deb` files
and I don't think it should be used to install things like Cygwin

also so far, I can not find any documentation for this appman.xml
eg. how to add an entry to add a custom template for example

So yeah I understand from the POV of someone using FD
it is probably easier to install other programs from FD itself

but it is not the distribution/installation solution we decided for redtamarin
as we need to support install not only for Windows but also Mac OS X and Linux

to be clear:
- installing redtamarin from FD  
  unlikely to happen
- adding a redtamarin template to FD  
  sure, but we need more doc/info

**Comment by Neverbirth** [comment]
As you say this wouldn't cover all your needs, the proposal is not to make FD the distribution mechanism for redtamarin, simply to make redtamarin more accessible to FD users.

I don't know if there is documentation of the format used, but I'd say it's easy to grasp by looking into the current file.

**Comment by zwetan** [comment]
maybe you can contribute a FD template file for redtamarin ?

**Comment by ajwfrost** [comment]
FD is Windows only anyway I believe? But I've just started looking at that: found a link:
http://www.flashdevelop.org/community/viewtopic.php?t=7908
This is more for the project template rather than adding it to appman.xml (I think adding an entry for appman.xml would be relatively trivial but I'm not sure how to get it into the FlashDevelop distribution!)
The project template was pretty useful although needs to be updated somewhat to work with the latest RedTamarin SDK. But I'm up and running with FlashDevelop + RedTamarin now, building/running working well.

**Comment by Neverbirth** [comment]
Yes, sadly at the moment FD is Windows only, but AFAIK it works nicely together with Crossover in other OSs.

To get the entry in appman.xml you'd simply have to make a pull request with the xml modifications.

**Comment by zwetan** [comment]
all I'm saying is Redtamarin have to distribute for many platforms. not just Windows
and in term of tooling we are much closer to the system than just "an exe to install"

once you have Cygwin setup and installed the redtamarin-sdk, the tools are available everywhere in your command-line, and this kind of setup should work for anything, wether you prefer to use FlashDevelop, or any other IDE, it should just works

So it's not that we don't want to support Flash Develop, but we can not change the way Redtamarin get installed to fit just the case of Flash Develop.

Provided you have installed the redtamarin-sdk, once you are inside Flash Develop you would just need to reference the `redtamarin.swc` and compile your main ActionScript 3 class with `redbean` on the command-line.

So yeah a FD project template for Redtamarin or as3shebang would be nice, but right now we don't have the time to do it, if you have something working, even a simple example that "works for you", send us the template and we'll integrate it.

For example in : `/extras/flashdevelop`
like what we did with [Sublime Text](https://github.com/Corsaair/redtamarin/blob/master/extras/sublime/info.txt)

and probably send a pull request to the FD project
note: you can do that too

and this project `redtamarin` can take pull requests too

**Comment by ajwfrost** [comment]
Agreed. I've adapted that earlier FD project template - it will need a bit more work but when I'm ready I'll share it and see whether I can push this over to the FD folk too...
Currently (as an aside) I've got redtamarin compiling on Windows (Cygwin) but having problems on Linux (an old Fedora box, I'll move onto Ubuntu shortly perhaps), and am having a play. I like it :-)

**Comment by zwetan** [comment]
that sound great :) for the FD project template.

for the other parts

> Currently (as an aside) I've got redtamarin compiling on Windows (Cygwin)

I documented it but I was not sure anyone would try, glad it worked :)

> but having problems on Linux (an old Fedora box, I'll move onto Ubuntu shortly perhaps)

if it's for the compiling, not sure I don't know very well Fedora
but if you are only interested to install the redtamarin-sdk there (and run the exe)

using [alien](http://manpages.ubuntu.com/manpages/gutsy/man1/alien.1p.html) to produce a tgz
should help, something like `$ alien --to-tgz -scripts redtamarin-sdk_0.4.1-1_amd64.deb`

please look at issue #57 

you are also welcome to open an issue for Fedora support
I don't have time to test under a VM but I can provide some pointers
for dependencies or whatnot

technically there is no reason redtamarin could not run under Fedora :)

> I like it :-)

that make my day :)

**Comment by zwetan** [comment]
I personally will not support anything Flash Develop

if someone want to propose contributions they are welcome
if it make sense, tested and it work "as is" I will add it in the distribution

issue closed so far
